#!/bin/csh -f

# runs ELAS 

# example of a "run" script expected for each stereo algorithm in alg-XXX directory

if ($#argv != 1) then
  echo "usage: run <dataset>"
  exit 1
endif

set dataset = $1

set p = $0:h
if ($p == $0) set p = .
set p = $p/Release

set tmplog = $p/../output/tmp-log.txt

set im0 = $p/../../trainingF/$dataset/im0.png
set im1 = $p/../../trainingF/$dataset/im1.png
set outfolder = $p/../../trainingF/$dataset/
set maxdisp = `awk -F= '/ndisp/ {print $2}' $p/../../trainingF/$dataset/calib.txt` 

(set echo; $p/alg-stereoMaxTree $im0 $im1 $maxdisp ../trainingF/$dataset disp0MaxTreeS_s)

