#!/bin/csh -f

if ($#argv != 1) then
  echo "usage: run_trimbot <dataset>"
  exit 1
endif

set dataset = $1

set p = $0:h
if ($p == $0) set p = .
set p = $p

set maxdisp = 35

set i = 1
while ( $i <= 9 )
	set im0 = $p/../trimbotF/$dataset/vcam_0_f0000$i'_undist.png'
	set im1 = $p/../trimbotF/$dataset/vcam_1_f0000$i'_undist.png'
	set outfolder = $p/../trimbotF/$dataset
	(set echo; $p/main $im0 $im1 $maxdisp $outfolder $i)
	@ i++
end

while ( $i <= 99 )
	set im0 = $p/../trimbotF/$dataset/vcam_0_f000$i'_undist.png'
	set im1 = $p/../trimbotF/$dataset/vcam_1_f000$i'_undist.png'
	set outfolder = $p/../trimbotF/$dataset
	
	(set echo; $p/main $im0 $im1 $maxdisp $outfolder $i)
	@ i++
end

while ( $i <= 100 )
	set im0 = $p/../trimbotF/$dataset/vcam_0_f00$i'_undist.png'
	set im1 = $p/../trimbotF/$dataset/vcam_1_f00$i'_undist.png'
	set outfolder = $p/../trimbotF/$dataset
	
	(set echo; $p/main $im0 $im1 $maxdisp $outfolder $i)
	@ i++
end