#!/bin/csh -f

if ($#argv != 1) then
  echo "usage: run_middleburry <dataset>"
  exit 1
endif

set dataset = $1

set p = $0:h
if ($p == $0) set p = .
set p = $p

set im0 = $p/../trainingF/$dataset/im0.png
set im1 = $p/../trainingF/$dataset/im1.png
set outfolder = $p/../trainingF/$dataset/
set maxdisp = `awk -F= '/ndisp/ {print $2}' $p/../trainingF/$dataset/calib.txt` 

(set echo; $p/main $im0 $im1 $maxdisp ../trainingF/$dataset disp0MaxTreeS_s)